name: advanceimagepicker
description: an advance image picker with cropper
version: 0.0.2
author: sajjad arvin
homepage: https://github.com/sajjadws/advance_image_picker

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^0.1.3
  image_crop: ^0.3.2
  image_picker: ^0.6.6+4
  cached_network_image: 2.0.0-rc
  fluster: ^1.1.2
  camera: ^0.5.7+4


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/

  fonts:
    - family: IranSans
      fonts:
        - asset: assets/fonts/IRANSans.ttf
    - family: Ace Records
      fonts:
        - asset: assets/fonts/Ace Records.ttf